name: verify

on:
  push:
    branches: [master]
  pull_request_target:

jobs:
  all:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install
        run: npm install

      - name: Build
        run: npm run build
        env:
          FORCE_COLOR: 3
          TERM: xterm-256color

      - name: Lint
        run: npm run lint
        env:
          FORCE_COLOR: 3
          TERM: xterm-256color